version: "3.9"
services:
  spring-app:
    build: .
    ports:
      - 8080:8080
    environment:
      VETAPP_DB_PASS: FYucJX0tkKO5
      VETAPP_DB_URL: jdbc:postgresql://ep-tiny-bar-a4cvqwn4.us-east-1.pg.koyeb.app/
      VETAPP_DB_NAME: koyebdb
      VETAPP_DB_USER: koyeb-adm

    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: FYucJX0tkKO5
      POSTGRES_DB: koyebdb
